# https://blog.liblab.com/using-github-graphql-api-with-github-actions
# https://gitprotect.io/blog/optimizing-github-actions-with-github-graphql-api/#Setting_up_GitHub_GraphQL_API_with_GitHub_Actions

name: Get GQL
on:
  workflow_dispatch:

jobs:
  fetch-repo-id:
    runs-on: ubuntu-latest
    steps:
      - name: Query GitHub GraphQL API
        id: fetch_data
        uses: actions/github-script@v7
        env:
          SECRETS: ${{ toJSON(secrets) }}
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const secret = JSON.parse(process.env.SECRETS);
            const query = `
              query {
                organization(login: "suptext-hq") {
                  projectsV2(last: 100,orderBy: {field:CREATED_AT,direction:DESC}) {
                    nodes {
                      id
                      title
                      template
                      createdAt
                    }
                  }
                }
              }`;
            const response = await github.graphql(query,{  
              headers: {
                  authorization: `token ${secret.GH_READ_PROJECTS}`,
                }
              });
            return response.repository.id;
      - name: Get result
        run: echo "${{steps.fetch_data.outputs.result}}"
          
