# https://blog.liblab.com/using-github-graphql-api-with-github-actions
# https://gitprotect.io/blog/optimizing-github-actions-with-github-graphql-api/#Setting_up_GitHub_GraphQL_API_with_GitHub_Actions
# https://stackoverflow.com/questions/77528848/github-graphql-api-how-to-retrieve-issues-project-items/77799377#77799377

name: Get project IDs
on:
  workflow_dispatch:

jobs:
  logProjectIDs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_project_ids
        with:
          query: |
            query {
              node(id: "PVT_kwDOCrWuKc4Am5oU") {
                ... on ProjectV2 {
                  statusUpdates(last: 1) {
                    nodes {
                      status
                      createdAt
                    }
                  }
                  items(last: 20) {
                    nodes {
                      id
                      fieldValues(first: 8) {
                        nodes {
                          ... on ProjectV2ItemFieldTextValue {
                            text
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldDateValue {
                            date
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            description
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          variables: |
            org: ${{ github.repository_owner }}
            repo: ${{ github.event.repository.name }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_READ_PROJECTS }}
      - run: "echo '${{ steps.get_project_ids.outputs.data }}'"
