name: Get user ID
on:
  workflow_dispatch:

jobs:
  logUserID:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_user_id
        with:
          query: |
            query {
              user(login: "suptext") {
                id
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'User Id: ${{ steps.get_user_id.outputs.data }}'"
